//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiserObjectify.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiserObjectify.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public Biser.Encoder BiserEncoder(Biser.Encoder existingEncoder = null)
        ///        {
        ///            Biser.Encoder encoder = new Biser.Encoder(existingEncoder);
        ///
        ///{@ContentEncode}
        ///
        ///            return encoder;
        ///        }
        ///
        ///
        ///        public static {@ObjName} BiserDecode(byte[] enc = null, Biser.Decoder extDecoder = null)
        ///        {
        ///            Biser.Decoder decoder = null;
        ///            if (extDecoder == null)
        ///            {
        ///                if (enc == null || enc.Length == 0)
        ///                    return null; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tmplBinary {
            get {
                return ResourceManager.GetString("tmplBinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///
        ///namespace {@NamespaceName}
        ///{
        ///
        ///	public partial class {@ObjName} : {@IfcJson} {@IfcComma1} {@IfcBinary}
        ///	{
        ///		{@ContentJson}
        ///
        ///		{@ContentBinary}
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string tmplBiserContainer {
            get {
                return ResourceManager.GetString("tmplBiserContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void BiserJsonEncode(Biser.JsonEncoder encoder)
        ///	{
        ///{@ContentJsonEncode}
        ///	}
        ///
        ///	public static {@ObjName} BiserJsonDecode(string enc = null, Biser.JsonDecoder extDecoder = null, Biser.JsonSettings settings = null)
        ///	{
        ///		Biser.JsonDecoder decoder = null;
        ///
        ///		if (extDecoder == null)
        ///		{
        ///			if (enc == null || String.IsNullOrEmpty(enc))
        ///				return null;
        ///			decoder = new Biser.JsonDecoder(enc, settings);
        ///			if (decoder.CheckNull())
        ///				return null;
        ///		}
        ///		else
        ///			decoder = extDecoder;
        ///
        ///		{@Ob [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tmplJson {
            get {
                return ResourceManager.GetString("tmplJson", resourceCulture);
            }
        }
    }
}
